pub const ENV_KEY_ALLOC_CONSOLE: &str = "RECORDIN_ALLOC_CONSOLE";
pub const ENV_KEY_LOG_DIR: &str = "RECORDIN_LOG_DIR";

pub const ENV_KEY_TARGET_REGEX: &str = "RECORDIN_TARGET_REGEX";
pub const ENV_KEY_AGGRESSIVE: &str = "RECORDIN_AGGRESSIVE_DLL_INJECT";
pub const ENV_KEY_IS_CLI: &str = "PROCESS_IS_RECORDIN_CLI";
pub const ENV_KEY_FORCE_TICK_THRESHOLD: &str = "RECORDIN_FORCE_TICK_THRESHOLD";

pub const ENV_KEY_FPS_F64_HEX: &str = "RECORDIN_FPS_F64_HEX";
pub const ENV_KEY_GRAPHICS_SYSTEM: &str = "RECORDIN_GRAPHICS";
pub const ENV_KEY_VIDEO_ARGS: &str = "RECORDIN_VIDEO_ARGS";
pub const ENV_KEY_VIDEO_ENCODER: &str = "RECORDIN_VIDEO_ENCODER";
pub const ENV_KEY_VIDEO_OUTPUT: &str = "RECORDIN_VIDEO_OUTPUT";

pub const ENV_KEY_SOUND_SYSTEM: &str = "RECORDIN_SOUND";
pub const ENV_KEY_AUDIO_OUTPUT: &str = "RECORDIN_AUDIO_OUTPUT";
